name: Deploy to Server

on:
  push:
    branches:
      - "main"

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: Austin-Server
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Copy Static Files
        run: cp -r static/ /var/www/aaarc/static/
      - name: Build
        run: cargo build --release
      - name: Copy Binary
        run: cp target/release/aaarc /var/www/aaarc/aaarc
      - name: Restart Server
        run: systemctl restart aaarc