name: Deploy to Server

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build_api:
    runs-on: gitlab
    steps:
      - name: Setup
        uses: actions/checkout@v4
      - name: Deploy
        run: docker compose up --build -d
